### ISSUE TITLE
[minor] Dead link to doc

### ISSUE THREAD

**Issue by bilderbuchi** [Exopy/exopy_pulses#20]
In the repository description, the link to the docs is wrong (needs to reflect the rename to exopy) 
http://ecpy-pulses.readthedocs.io/
Also, it's maybe a good idea to add that link to the Readme, too.

**Comment by MatthieuDartiailh** [comment]
Thanks for catching it. Will fix.

**Comment by MatthieuDartiailh** [comment]
The README needs a larger refactor than just the link to the docs. Will do that later. The issue with the doc link if fixed.

**Comment by bilderbuchi** [comment]
thanks :-)
